platform :ios, '9.0'

target 'Haxball' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CDJoystick', '~> 0.1.0'
  # Pods for footballStats

  target 'HaxballTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HaxballUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
